font:
  url: 'https://github.com/tommyngx/style/blob/main/Poppins.ttf?raw=true'
  path: 'Poppins.ttf'
  size: 12

model_name_map:
  deepsurv: 'DeepSurv'
  deephit: 'DeepHit'
  cox_ph: 'CoxPH'
  gboost: 'GradientBoosting'
  svm: 'SVM-Surv'
  rsf: 'RSurvivalForest'
  kaplan_meier: 'KaplanMeier'
  random: 'Random'

color_list:
  - "#2ca02c"
  - "#8c564b"
  - "#9467bd"
  - "#d62728"
  - "#ff7f0e"
  - "#e377c2"
  - "#7f7f7f"
  - "#bcbd22"
  - "#17becf"

cols_22:
  - age
  - education
  - weight
  - height
  - smoke
  - drink
  - no_falls
  - fx50
  - physical
  - hypertension
  - copd
  - parkinson
  - cancer
  - rheumatoid
  - cvd
  - renal
  - depression
  - diabetes
  - Tscore
  - protein
  - calcium
  - coffee

cols_11:
  - age
  - weight
  - height
  - fx50
  - smoke
  - drink
  - rheumatoid
  - Tscore

cols_5:
  - age
  - weight
  - no_falls
  - fx50
  - Tscore